# The NA12878 exome from EdgeBio
# http://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#exome-with-validation-against-reference-materials
# Coverage obtained with several parameter set permutations for comparison

